### ISSUE TITLE
could not handle batch request

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-phenote#32]
Could not successfully handle batch request. Exception: org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException. Could not validate the id: MESH:C537176 Could not successfully handle batch request. Exception: org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException. Could not validate the id: MESH:C537176

Is it the case that only HP terms are accepted? Perhaps at present, we could at least change the tooltip accordingly.

**Comment by DoctorBud** [comment]
This has been fixed. Closing this ticket. Reopen a new ticket with more details about how to duplicate, if this reoccurs, please.
