### ISSUE TITLE
Create a web page and link from old Phenote website

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-phenote#4]
We would like the monarch phenotype noctua interface to have its own distinct web presence. This could simply be the instance of the tool itself (as http://noctua.berkeleybop.org is the instance for GO); if so we need a way to configure the front page a bit more to provide context specific to the instance. We would then coordinate larry to deploy the instance (presumably something like phenotua.monarchinitiative.org).

Or in the interim just an about page that lives somewhere.

We will also need a link to this page from the old phenote website: http://phenote.org/ saying "we are currently developing a web-based version of phenote, head on over to URL to find out more". @nlwashington / @kltm do we remember how to edit that page?

This all presupposes we have figured out the name: phenotue vs webphenote vs...

**Comment by nlwashington** [comment]
perhaps the new name should be something without "pheno" in it?  the "pheno" space is getting crowded.   (personally i find phenotua awkward to pronounce and spell).

but generally +1 to update the web presence.  i recall hosting the website in svn, but don't recall how to edit.  maybe @nlharris will remember (i imagine she was the last to edit).

**Comment by kltm** [comment]
@cmungall When lsc was finally played off the stage by LBL security, its contents was dumped with a few other domains onto AWS. Manual access and changes only now.

**Comment by nlharris** [comment]
Sorry, I can't remember how we accessed the website.

**Comment by jmcmurry** [comment]
I also find "phenotua awkward to pronounce and spell".
Perhaps the ship has sailed, but I think Phenote2 is better.

**Comment by DoctorBud** [comment]
The old http://phenote.org site appears to be offline.

We've decided on WebPhenote as the name, and the Monarch version (Disease/Phenotype/Evidence) is deployed at http://create.monarchinitiative.org

This ticket is now irrelevant. Closing it.
